// Throttle credential-sensitive endpoints (login, register, forgot/reset password)
// to blunt brute-force / credential-stuffing / password-spray (OWASP API2/API4).
// Per-IP, configurable via env. The rateLimit plugin is registered global:false,
// so only routes carrying this opt in.
const authRateLimit = {
  max: Math.floor(Number(process.env.AUTH_RATELIMIT_MAX) || 10),
  timeWindow: Math.floor(Number(process.env.AUTH_RATELIMIT_WINDOW) || 60000)
}

// Per IP, on top of the per-flow and per-subject ceilings of the flow store, which are the real
// gates (F44). `cancel` has none: it can only end the caller's own flow.
const perMinute = (max: number) => ({ max, timeWindow: 60000 })

export default {
  config: {
    title: 'Authentication functions',
    description: 'Authentication functions',
    controller: 'controller',
    tags: ['auth'],
    deprecated: false,
    version: false,
    enable: true
  },
  routes: [
    {
      method: 'POST',
      path: '/register',
      roles: [],
      handler: 'auth.register',
      middlewares: ['global.preAuth', 'global.postAuth'],
      rateLimit: authRateLimit,
      config: {
        title: 'Register new user',
        description: 'Register a new user',
        body: { $ref: 'authRegisterBodySchema#' },
        response: {
          200: { $ref: 'authRegisterResponseSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/unregister',
      roles: [],
      handler: 'auth.unregister',
      middlewares: ['global.preAuth', 'global.postAuth'],
      config: {
        title: 'Unregister existing user (actually disables it)',
        description: 'Unregister an existing user (actually disables it)',
        body: { $ref: 'authLoginBodySchema#' },
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/validate-password',
      roles: [],
      handler: 'auth.validatePassword',
      middlewares: [],
      config: {
        title: 'Validate password',
        description: 'Validate password if valid and usable',
        body: { $ref: 'onlyPasswordSchema#' },
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/change-password',
      roles: [],
      handler: 'auth.changePassword',
      middlewares: ['global.isAuthenticated'],
      config: {
        title: 'Change password',
        description: 'Change password for an existing user',
        body: { $ref: 'authChangePasswordBodySchema#' },
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/confirm-email',
      roles: [],
      handler: 'auth.confirmEmail',
      middlewares: [],
      config: {
        title: 'Confirm email',
        description: 'Confirm email for an existing user',
        body: { $ref: 'onlyCodeSchema#' },
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/forgot-password',
      roles: [],
      handler: 'auth.forgotPassword',
      middlewares: ['global.preForgotPassword', 'global.postForgotPassword'],
      rateLimit: authRateLimit,
      config: {
        title: 'Forgot password',
        description:
          'Forgot password for an existing user given the email or username. Create a reset token, used by "POST /auth/reset-password".',
        body: { $ref: 'authForgotPasswordBodySchema#' },
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/reset-password',
      roles: [],
      handler: 'auth.resetPassword',
      middlewares: [],
      rateLimit: authRateLimit,
      config: {
        title: 'Reset password',
        description:
          'Reset password for an existing user given the reset token (generated by "POST /auth/forgot-password").',
        body: { $ref: 'resetPasswordBodySchema#' },
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/login',
      roles: [],
      handler: 'auth.login',
      middlewares: ['global.preAuth', 'global.postAuth'],
      rateLimit: authRateLimit,
      config: {
        title: 'Login',
        description: 'Login authentication',
        body: { $ref: 'authLoginBodySchema#' },
        response: {
          200: { $ref: 'authLoginResponseSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/logout',
      roles: [],
      handler: 'auth.logout',
      middlewares: [],
      config: {
        title: 'Logout',
        description: 'Logout (clears cookie if in cookie mode)',
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/refresh-token',
      roles: [],
      handler: 'auth.refreshToken',
      middlewares: [],
      config: {
        title: 'Refresh authentication token',
        description: 'Refresh login authentication token',
        body: { $ref: 'authRefreshTokenBodySchema#' },
        response: {
          200: { $ref: 'authRefreshTokenResponseSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/invalidate-tokens',
      roles: [],
      handler: 'auth.invalidateTokens',
      middlewares: ['global.isAuthenticated'],
      config: {
        title: 'Invalidate all tokens',
        description: 'Closes every session of the caller and rotates the public identifier',
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'GET',
      path: '/sessions',
      roles: [],
      handler: 'auth.listSessions',
      middlewares: ['global.isAuthenticated'],
      config: {
        title: 'The sessions of the caller',
        description: 'Where this account is logged in, with the current session marked',
        response: {
          200: { $ref: 'authSessionsResponseSchema#' }
        }
      }
    },
    {
      method: 'DELETE',
      path: '/sessions/:id',
      roles: [],
      handler: 'auth.revokeSession',
      middlewares: ['global.isAuthenticated'],
      config: {
        title: 'Close one session',
        description: 'Closes a session of the caller by its id; a session of somebody else answers 404',
        params: { $ref: 'onlyIdSchema#' },
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },

    {
      method: 'POST',
      path: '/mfa/setup',
      roles: [],
      handler: 'auth.mfaSetup',
      middlewares: ['global.isAuthenticated'],
      config: {
        title: 'Setup MFA',
        description: 'Generate secret and QR code for MFA setup',
        response: {
          200: { $ref: 'authMfaSetupResponseSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/mfa/enable',
      roles: [],
      handler: 'auth.mfaEnable',
      middlewares: ['global.isAuthenticated'],
      // Throttle TOTP attempts to curb online brute-force of the 6-digit code (S11).
      rateLimit: { max: 10, timeWindow: 60000 },
      config: {
        title: 'Enable MFA',
        description: 'Enable MFA by verifying a token against the generated secret. Returns tokens on success.',
        body: { $ref: 'authMfaEnableBodySchema#' },
        response: {
          200: { $ref: 'authLoginResponseSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/mfa/verify',
      roles: [],
      handler: 'auth.mfaVerify',
      middlewares: [],
      // Throttle TOTP attempts to curb online brute-force of the 6-digit code (S11).
      rateLimit: { max: 10, timeWindow: 60000 },
      config: {
        title: 'Verify MFA',
        description: 'Verify MFA token during login to obtain final JWT',
        body: { $ref: 'authMfaVerifyBodySchema#' },
        response: {
          200: { $ref: 'authLoginResponseSchema#' },
          202: { $ref: 'authMfaChallengeSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/mfa/disable',
      roles: [],
      handler: 'auth.mfaDisable',
      middlewares: ['global.isAuthenticated'],
      config: {
        title: 'Disable MFA',
        description: 'Disable MFA for the current user',
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'GET',
      path: '/flow/options',
      roles: [],
      handler: 'flow.options',
      rateLimit: perMinute(60),
      config: {
        title: 'Login methods',
        description: 'The identifiers of the tenant plane, without creating anything',
        response: {
          200: { $ref: 'authFlowOptionsResponseSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/flow/start',
      roles: [],
      handler: 'flow.start',
      middlewares: ['global.preAuth', 'global.postAuth'],
      rateLimit: authRateLimit,
      config: {
        title: 'Start a login',
        description: 'Runs the identifier named by `method`: 200 with the session when nothing else is owed, 202 with the next stage otherwise',
        body: { $ref: 'authFlowStartBodySchema#' },
        response: {
          200: { $ref: 'authLoginResponseSchema#' },
          202: { $ref: 'authFlowPartialResponseSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/flow/step',
      roles: [],
      handler: 'flow.step',
      middlewares: ['global.preAuth', 'global.postAuth'],
      rateLimit: perMinute(10),
      config: {
        title: 'Answer the current stage',
        description: 'Verifies `method` for the flow of the credential, or starts its enrolment with `action: enrol`',
        body: { $ref: 'authFlowStepBodySchema#' },
        response: {
          200: { $ref: 'authLoginResponseSchema#' },
          202: { $ref: 'authFlowPartialResponseSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/flow/challenge',
      roles: [],
      handler: 'flow.challenge',
      rateLimit: perMinute(5),
      config: {
        title: 'Send a code again',
        description: 'Sends the code of a method of the current stage, within the ceilings of the flow',
        body: { $ref: 'authFlowChallengeBodySchema#' },
        response: {
          202: { $ref: 'authFlowPartialResponseSchema#' }
        }
      }
    },
    {
      method: 'POST',
      path: '/flow/cancel',
      roles: [],
      handler: 'flow.cancel',
      config: {
        title: 'Abandon a login',
        description: 'Ends the flow of the credential, if there is one',
        body: { $ref: 'authFlowCancelBodySchema#' },
        response: {
          200: { $ref: 'defaultResponse#' }
        }
      }
    },
    {
      method: 'GET',
      path: '/flow/return/:method',
      roles: [],
      handler: 'flow.returnFrom',
      rateLimit: perMinute(20),
      config: {
        title: 'Return from a provider',
        description: 'Records the answer of an external provider in the flow its `state` names, then redirects to the console',
        // The tenant comes from the flow `state`: the navigation carries no token and no header.
        tenantFrom: 'flow-state'
      }
    },
    // The caller's own external identities (T-12.27): seen and removed, not added (F48).
    {
      method: 'GET',
      path: '/identities',
      roles: [],
      handler: 'identities.list',
      middlewares: ['global.isAuthenticated'],
      config: {
        title: 'The external identities of the caller',
        description: 'The provider accounts linked to this account',
        response: { 200: { $ref: 'externalIdentityListSchema#' } }
      }
    },
    {
      method: 'DELETE',
      path: '/identities/:id',
      roles: [],
      handler: 'identities.remove',
      middlewares: ['global.isAuthenticated'],
      config: {
        title: 'Remove one external identity',
        description: 'Unlinks a provider account of the caller; one of somebody else answers 404',
        params: { $ref: 'onlyIdSchema#' },
        response: { 200: { $ref: 'defaultResponse#' } }
      }
    }
  ]
}
