import crypto from 'crypto'
import fs from 'fs'
import path from 'path'

//
// Reading a migration set off disk (T-5.1).
//
// The format is plain SQL, generated by `drizzle-kit generate` and committed. Not a class,
// not a JSON description of a change: the thing that runs against a customer's database is
// the thing a reviewer reads, in the language the database speaks.
//
// Two rules the format carries with it:
//
//   - **order is the file name**, and the names are timestamps, so the order is the order
//     they were written in and no index file can disagree with the directory;
//   - **forward only**. There is no `down`, because `drizzle-kit` does not generate one and
//     because a `down` on a destructive migration restores the shape and not the data, which
//     is a promise that fails exactly when it is needed. Reversibility lives in the design
//     (expand/contract, see the README), not in a script that lies.
//
export interface MigrationFile {
  /** The file name without its extension: it is the identity, and it is the order. */
  readonly name: string
  readonly sql: string
  /** SHA-256 of the file, so an edited migration is caught rather than silently skipped. */
  readonly hash: string
}

/** `drizzle-kit` separates statements with this marker. Without it, the file is one statement. */
const BREAKPOINT = /^\s*--> statement-breakpoint\s*$/m

export function readMigrations(folder: string): MigrationFile[] {
  if (!fs.existsSync(folder)) return []

  return fs
    .readdirSync(folder)
    .filter((f) => f.endsWith('.sql'))
    .sort()
    .map((file) => {
      const sql = fs.readFileSync(path.join(folder, file), 'utf8')
      return {
        name: path.basename(file, '.sql'),
        sql,
        hash: crypto.createHash('sha256').update(sql).digest('hex')
      }
    })
}

/** The statements of one file, in order, with the empty tail a trailing breakpoint leaves. */
export function statementsOf(migration: MigrationFile): string[] {
  return migration.sql
    .split(BREAKPOINT)
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
}
